default:
    # Outside of Repo
    path_ds_jh_daily       : "../covid19-country-response/data-unshared/derived/john-hopkins-state.rds"
    path_ds_votes          : "../covid19-country-response/data-public/derived/us-2020-state-political-results.rds"
    path_ds_vote_pres_2020 : "../covid19-country-response/data-public/derived/us-2020-state-pres-results.rds"
